version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "development"
      - dependency-name: "@slack/web-api"
      - dependency-name: "common-tags"
      - dependency-name: "lodash"
      - dependency-name: "moment"
      - dependency-name: "moment-timezone"
      - dependency-name: "scrape-it"
      - dependency-name: "tsscmp"
