name: Test (AWS)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
      working-directory: aws/

    - name: Install dependencies
      run: npm ci
      working-directory: aws/

    - name: Build
      run: npm run build
      working-directory: aws/

    - name: Run tests
      run: npm test
      working-directory: aws/
    
    - uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true
        working-directory: aws/
