name: Test (AWS)

on:
  push:
  pull_request:

permissions:
  contents: read

defaults:
  run:
    working-directory: aws/

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat aws/.nvmrc)
      id: nvm

    - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Setup test
      run: bash ci/test-setup.sh

    - name: Run tests
      run: yarn run test:ci
    
    - uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true
        directory: aws/
