name: Test (AWS)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat aws/.nvmrc)
      id: nvm

    - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: yarn/

    - name: Add empty .env.local.json
      run: echo '{}' > .env.local.json
      working-directory: aws/

    - name: Run tests
      run: yarn run test:ci
      working-directory: aws/
    
    - uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true
        directory: aws/
